cc_library(
  name="decl",
  hdrs=[
    "include/about.hpp",
  ],
  strip_include_prefix="include",
  include_prefix="about",
  linkopts=[],
  deps=[],
  visibility=["//visibility:public"]
)

cc_library(
  name="utility",
  hdrs=glob(["include/utility/*.hpp"]),
  strip_include_prefix="include/utility",
  include_prefix="about",
  linkopts=[],
  deps=[],
  visibility=["//visibility:public"]
)
